name: MoreAppsKitExample
options:
  bundleIdPrefix: com.zhanggen
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  MoreAppsKit:
    path: ../

targets:
  MoreAppsKitExample:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: MoreAppsKit
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.0"
